adminUser:
  password: vault:pr-705-1arc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-705-1arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-705-1arc/prow:hmacToken
segmentWriteKey: vault:pr-705-1arc:segmentWriteKey
